import RequestProject.Construction.MassPool
import RequestProject.R2Weights

open Finset BigOperators GlobalControl

noncomputable section

namespace CircleMethod

/-!
# Consequences of a mass-batch supply (node C2, mechanism 3)

Single motivating question: **once `R2MassBatchSupply D` is in hand
(`Construction.MassPool`), what do we get for free?**  Two immediate
consequences (every batch edge is a semiprime, hence a period divisor) and
the canonical uniform `Weights` package generated from the load window,
consumed directly by `R2Certificates.lean`.

See `docs/construction-redesign.md` node C2.
-/

namespace R2MassBatchSupply

variable {T : Finset ℕ} {b : ℕ} {D : R2ConcreteData T b}

/-- Products of two ordered block-support primes are semiprimes. -/
lemma q_semiprime (S : R2MassBatchSupply D) :
    ∀ e ∈ D.Q, IsSemiprime e := by
  intro e he
  obtain ⟨p, q, hp, hq, hpq, rfl⟩ := S.hQpair e he
  exact ⟨p, q, blockSupport_prime D.BS hp, blockSupport_prime D.BS hq, hpq, rfl⟩

/-- Every mass-batch edge divides the concrete period. -/
lemma q_dvd_period (S : R2MassBatchSupply D) :
    ∀ e ∈ D.Q, e ∣ D.L := by
  intro e he
  obtain ⟨p, q, hp, hq, hpq, rfl⟩ := S.hQpair e he
  have hpprime : Nat.Prime p := blockSupport_prime D.BS hp
  have hqprime : Nat.Prime q := blockSupport_prime D.BS hq
  have hpdvd : p ∣ ∏ r ∈ blockSupport D.BS, r :=
    Finset.dvd_prod_of_mem id hp
  have hqdvd : q ∣ ∏ r ∈ blockSupport D.BS, r :=
    Finset.dvd_prod_of_mem id hq
  have hcop : Nat.Coprime p q := by
    exact hpprime.coprime_iff_not_dvd.mpr fun hdiv => by
      have hp_eq_q : p = q := (Nat.prime_dvd_prime_iff_eq hpprime hqprime).mp hdiv
      omega
  have hpq_dvd : p * q ∣ ∏ r ∈ blockSupport D.BS, r :=
    hcop.mul_dvd_of_dvd_of_dvd hpdvd hqdvd
  rw [R2ConcreteData.L]
  exact edge_dvd_primeSupportPeriod_of_mem_support hpq_dvd

/-- The canonical uniform weight package generated by the mass-batch load
window. -/
def weights (QB : R2MassBatchSupply D) (hb : 0 < b) :
    R2ConcreteData.Weights D :=
  let hwindow := D.total_recipLoad_window_of_residual
    QB.hloadDisj QB.hloadLower QB.hloadUpper
  R2ConcreteData.weights_of_recipLoad_window D hb hwindow.1 hwindow.2

end R2MassBatchSupply

end CircleMethod

end
