import RequestProject.R2MassBatchSupply
import RequestProject.R2Weights

open Finset BigOperators GlobalControl

noncomputable section

namespace CircleMethod

/-!
# R2 weights from a mass-batch supply

A `R2MassBatchSupply D` already carries the residual reciprocal-load window.
This leaf turns that window into the canonical uniform `Weights D` package.
-/

namespace R2MassBatchSupply

variable {T : Finset ℕ} {b : ℕ} {D : R2ConcreteData T b}

/-- The canonical uniform weight package generated by the mass-batch load
window. -/
def weights (QB : R2MassBatchSupply D) (hb : 0 < b) :
    R2ConcreteData.Weights D :=
  let hwindow := D.total_recipLoad_window_of_residual
    QB.hloadDisj QB.hloadLower QB.hloadUpper
  R2ConcreteData.weights_of_recipLoad_window D hb hwindow.1 hwindow.2

end R2MassBatchSupply

end CircleMethod

end
